install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B
  -V
script: mvn test -P !build-extras -B
cache:
  directories:
  - "~/.m2/repository"
before_install:
- chmod +x ./cd/before-deploy.sh
- chmod +x ./cd/deploy.sh
after_success:
- "./cd/before-deploy.sh"
- "./cd/deploy.sh"
language: java
jdk:
- oraclejdk9
env:
  global:
  - secure: hT/yrItKbhG+FlKomJxvNKQp8X/1ETqmyT//g5eGQ+WbiYkKEFe112xSyk8xE68xQ6nqpH1WA3I5PS4lzs+/XDs1egHKg4alGor7h++GFjSQRYm3V19Gq8Z18D8VNe5V9cidP0l9bMY/iWk/zawInqeGBYmhgTZbhpomnVtaIl5MHORZp4doxGtVyid5U/faRIo7RNsmJ0nbh0IFUTof1C1rurR+AltFsyrUhlubc6pzPp2jxhyhbh5myDUOekcQoK19a7VkltPcu5iMzXApmNXQ5kxCWkFa7PiGDD8WIUFp3dZoPaA/ZePM9Qsv8KLJM1XEvATL7JzI2+k4AaZclRLkxwZbKfj95XVwgPEoPNivG36N0Wp1CWoCArlknffofSU+0cerOSvfVp0g02IUU3PAcVMOafcO6WiCbYskNJm4yfRX2r8X3PzrFvbGCuk0Za9g02Uxl6GuJkYad+gTCiJxpDo3qvquU9va0T4imV+wUZq2O/MYVxi080Ul2lojGixEO9gYY9hg2bJT/G4gXG2tvTu2VWJ5PX6ZYQXU8CoA1yKXq5G2yX0Ii+KV7LPeTlld4C88kOwRNRvW4gtb4uLkVMO5Pdg5kI4SKBLrMmdnGx+50k6wuz/dOY49E0yuzfohxcBfwBZbODo3oI+Xg7fF9mz0WCDh8sHLzJAQD00=
  - secure: vIuBl4yVLwxkUlVjIVux9SHFfNtdx5c+DXUs3YP5l4hGpJuYBydJlmRhKA3j2ZX/nNpt2uYnCSEw8V/7xo9cMhOJ7g3tC503fTrMlC91IGni3nqG6nD4tCZZTY39XiS69nfbNhjl8HXrbPpyo0JWrH0dy66nOQwenENT2oI9A/NQNwFZceQiopNJZiFHnozbwT+//+91oN5eXimN7WY3XPxCozCXzGtbCsGMXu6fWZjMkJpheEBeKOqEWhBJ1rPsdknBq/Yy80w+/dU0ipvmE0lcZpSU9HAuPUtGDyWWVzdD80GS1hZuJ1fV4xMiLq8GFyWgCSMxncuHMlXgRAgyyqHm6ch6Eua/S3zYCd2hv9GigAN7B2mOFSZ+dafsLdIJLfgPHnZ3EsQvtjwt196WSdF1+21OoWtdFs2vWGk29f/KZpGNpqYnQ3CFxyaFMbBbrCKGffQZaErnXb4Bt5hXu9RrNsWfqe/JHBJJHoaRRZuae9eUYG93e/WfiPNbEb/yVdwmxheXltfogvRIRpYzSwHImtL9+JLAdPwN45vniJsn3p5AYMLYor1DHn3Dc2RadYUftoQTtlfPAKGwSE5XrnnYBFKTslJfiqgzOIBvLKkNQ+D53kCH+dVewq/ODw1DpzmVPhC/s9R6QQgCBqonux59ClWcih9nCFdQ81G4q2k=
