install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B
  -V
script: mvn test -P !build-extras -B
cache:
  directories:
  - "~/.m2/repository"
before_install:
- chmod +x ./cd/before-deploy.sh
- chmod +x ./cd/deploy.sh
after_success:
- "./cd/before-deploy.sh"
- "./cd/deploy.sh"
language: java
jdk:
- oraclejdk9
env:
  global:
  - secure: BO/vfX0E2/31UxWcGaOwlnTsnN+rWigoWLrMtG77nWubYE+sDKaR9A5/ACyLFyoKT/91qy2SfXF3wctZB9KM1fij1fTRaJBg85VmaSVfGs3E/hF9AK/WCkfVa4t6AeiI51OBnt58aAkvn0c7FJmpfv/v65t5tnNalw6UHrzXs5/aZGcGsRcfTqqh3gtUFMdXwHLnqMAAWOPVnRlRNkuojD/VrBbCvAeI0P9iexw8xnySUy7mkTRgLseM6jcWYpoKAmFmoYcFJQiKgv3/EHxAfJCoDIEtmN6HtUDR0F/s4IwnViY3lHowQQn3CWKmPkw2ibGvhmxQGeF6CDngeFu/kr2k+qpDwvSoRnAyW/oSbR26eEZd30xiPpr++DHwH84LB5kT6Ks9xFnK6bJo4bVlPhkqlmm1YGUS2WVDUDIzPKMVqEr9DpsyO8VVMUBdWUkiEo1tww4Vm/B43erEcudo2laMFNtzeP1UuQhcnMspGcoLXfY87TyUeoQ/OYol9erZ/JZGiKqmqS7B9HT8qc+Hbmh7gw2XSm/3PdgAuO7TGYx7UTtW8W4Y7MzIkYdBQvCEy5/soxm3Qs+6VUt4mjR68qHwZlvcecfQJQSoEkIA/lCnJ/0z6nh+5d1Qo75YQv0k6h3LMUeeW8hoCCmJceXq0upAFEUKj/BVlC0hq0vDWMU=
  - secure: ahV+xRADipNUGvBuBpmvgfiOcY5BIYtZXJpYbNmwzMlY9CbijAygStkef9b277izdcDKvFH1xOY3oh/T9OHXU+JCj3fCXf/CBbbTEsgg+QFAyEF7j7XNFCQr5VrbJZXQyQkTxsyElBXBuOR3tsGhoUywcufLP1EHmjfr6aybbtnhrq78bFVAiTumMcLaHXPm/gIfokwOt8bir3nZIFzD3+Ri9TSRGlp+a7LK94JeqeqBtOP68GPCMGHrmHs3hIg32beSZ0xCsvnbhWX12JDnPhpf9OCNP8Z7o4gwMCzV4KVkPdp8LSy03K/smywyRmLySlU1Sk2nvXUR8qLrFdLQFqQ3JYU0/9+mWpFl8bW6xvr8P4mLJw+8vRFb4Ko5MUjYy+SmPmcQmGQjWav+79/KPl36uS0KMqsBMpSpP0Ack4txH2O3Ap8q8LUx6iLrRAufo8ktA0TMOBAyN14SjBZwns+ThPV8xIXxWE+YQKmaWgM6FZyBZ3AWP1toq+YiXNnf3syAjTj3lVcwjo4Yi3doNOqrrawl6Xn8Rh7idtIH/Ce/BSl23Yam+YIEpRMA448jM7LKpoIl9I1SPf28FscyjkmKlecL9HZFqHe96ZRtAl48GWObEOmNiArifrNbuvTmyjr47g86RmoBxh6Mb7OGtSPgHXZMjcGk/dq1WPHbZys=
