install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B
  -V
script: mvn test -P !build-extras -B
cache:
  directories:
  - "~/.m2/repository"
before_install:
- chmod +x ./cd/before-deploy.sh
- chmod +x ./cd/deploy.sh
after_success:
- "./cd/before-deploy.sh"
- "./cd/deploy.sh"
language: java
jdk:
- oraclejdk9
env:
  global:
    secure: JosJ80hbJ1TB5m/vorfLFc+hTZTNPUni8iHQeX/33mnefklIZNgzWXnJH7sK0ggXIA1d6nzYiuic/hZ6Dj7oqKDhAvPgkRXkW79U189If60YFYSF2sai9bQGnDY7tL1uUO6rmmVAqEhU41XlVgGSUEn0PvzWdj+dYWRBeOFMi2AClzWy3eRp2m/kIuDjptkjCTjfiPXSz/Q1SMWSRbBQytzEQbtQjIE3w4Vjhisf8Z+FYa4WWnK0WtmbLq4XvWkJv+RFQ9Xbhy/aIcbQuJQ9EALY7yGx6dMT4l7fMbUGEuSm1mUTphROOSEjNEVO/qlDpdMq4ESBaG7ZtxyngKd4C5jCBVFxnc5tRr1fnVvZNPHz3aYRA49dg5168MRMP2ddMbKAeC8O6l5/0jY9N+WSZc6iHPzhNodyKqzBMvh0F3FGc0ymZhxojxeToZIfQ6FRcEy3bhxZHLhqhjoGnxwchxo4cof3SxXUjhFkRIap3vSqYNeNS7lkFDqdDteE4SgA8Xe1rzJQoA2qQSDMJLrdD5vFCfoHgxBBQoPc8qOg5wchrEIMUyCwLkdSSU5BxH2tYBrW7lE81+QVOZPzuOzaLolzW3VOVlJ4GvmG3/IJYrUe5aTJENhswoDFGpX7tWdjHgFgEkD/3Sj34Dpeu1+VXRo2MAeFFoG67Pu6CO55nZs=
