install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B
  -V
script: mvn test -P !build-extras -B
cache:
  directories:
  - "~/.m2/repository"
before_install:
- chmod +x ./cd/before-deploy.sh
- chmod +x ./cd/deploy.sh
after_success:
- "./cd/before-deploy.sh"
- "./cd/deploy.sh"
language: java
jdk:
- oraclejdk9
env:
  global:
  - secure: XKYPkz/d3/LeomAfBW3UWvUq6RoXY+xpTWppFe7jAJ0UgajlLo1c9RxD/leM7Xsqe2kkH3Dywyk/yAiWXMFpqu72nwpDWTktdDU7b5ITASahycJLq09kpfsk4GrLOyGgqtVuh9TcULQpaKEOUm7qR7k3C35BwoVSAJvSDdVMp/MjWiIks8z8tomRm0KV2YpqnwlXJjIjax7R33PWrZeSdkJMYWEJ6c+MMaRQKqR1gIZqf6iegbg1JDy7RiK1UJoWrLoC2KlI4Hwd2fh7ZLcxoZMQXQ6my7fji6l6tGLSlmXJKmPWQki7f8v1f9tMBHWljgHaO/XGzg29Ht06X+YZ6UtRRs6Py7Lpip75RWt9VHM6JSFLEp2eSwTNFdvKsk6FRvJsEqNHdEpo6zlMGt9M3B8mdnMaZhVckO/bIOqXCMxm23LKIrYbExBhMCf8SzMTifUkuXkbOWtCzoy+eFgdlUHwQSblGRoUUK6TlP4DrEviubaCmqwYjGwtA9exZLrnsdVYIOQ1VUh3Kez5+SarjeD0BYisyM8nHUpZCTVIUGUEt7nBfTbbtKDC6MypnVEN2Hrb5Psbb3JmVtmEcVf+Bh4+9eku8NncBGBjcQGiWE+2/gf9lL1fxmbL1lp/DRG2eI4KhFspZnvBNF4uyu28wQjSF8Ey7xm5kcgT6sHteAU=
  - secure: O21S7gRpMetXxkQjkW/zXDGalESlkLGits58HegGkBP9tW160zUo+2Z67B7jvrZm6EV06IcsM/UHskNNN6jtXgYLO3mBjLS7wn3MeDLt6VU6DitWVDB/4y/X4iP6xbF7p2INKJrTSbxD8ijEciuk4Pn+O934vFEQIVH2BMBIZxk8+SFdSFuzbz5atoj3b7GLdFjdrWY2NsJJ7u4z28SJdmUZwLgahrxP8V9IopNiSUtyZrqR/M4zYwV8KQR3Aawy+ScPdkeICzTb7W7UHANK7jX4tvrq8ZTBMq+0vmnwJmL7xK2guBduIfHRKCwyKg8gjc1qQx3JuW0oy8nGki89UyIAjsFHtNi/8/FbfWPQctCdlhCO8PB89PyHjik7XU5c58o8Q4PR6T5hsF3wrazyMVL5kG1U9b3tWGTJG10esV+/hfGpvQIssUyUDHCmkp0tE0HQGu9wSrth+TDODU2MnYiuDm4fBhoFfqxDOcQB5jM85QD35rLEH4qePjoDZWr9OWSQDaWO8Zn2isTlCi91aKF3z96gzBcu1iZ7FVzxzTOItwTvygoBih75TVJmPmeKkwxd7h9p3T/Lo7XY1cWRzAKVG9sXG2Ei0V2Hk6dZSWx+0xs4/GelPrcTLzuOgUYNcpwPBmAuwMZjHVaMRiugRbvkTSaHUk7w2C9JUtCNGC4=
